# Generated by Django 6.0.3 on 2026-03-24 13:23

import pets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(validators=[pets.validators.validate_date]),
        ),
    ]
