# Generated by Django 6.0.3 on 2026-04-10 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedissues',
            name='title',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportedissues',
            name='issue',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
    ]
