# Generated by Django 6.0.3 on 2026-04-12 11:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_reportedissues_title_alter_reportedissues_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedissues',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportedissues',
            name='issue',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30, message='Issue description must be at least 30 characters.')]),
        ),
    ]
