# Generated by Django 6.0.3 on 2026-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_reportedissues_created_at_alter_reportedissues_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedissues',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
