# Generated by Django 6.0.3 on 2026-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_tag_forumpost_created_on_forumpost_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
