# Generated by Django 6.0.3 on 2026-03-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pawmedicuser_profile_picture_userprofile_vetprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VetProfile',
        ),
    ]
