# Generated by Django 6.0.3 on 2026-03-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vetprofile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pawmedicuser',
            name='profile_picture',
        ),
    ]
