# Generated by Django 6.0.3 on 2026-04-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vetprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='vets', to='accounts.service'),
        ),
    ]
