# Generated by Django 6.0.3 on 2026-04-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_service_vetprofile_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetprofile',
            name='services',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
