# Generated by Django 6.0.3 on 2026-03-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VetProfile',
        ),
    ]
