# Generated by Django 6.0.3 on 2026-04-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_vetprofile_photo'),
        ('appointments', '0005_appointmentslot_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vets', to='accounts.vetprofile'),
        ),
    ]
